//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffeeshop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitems
    {
        public int id { get; set; }
        public int orderid { get; set; }
        public int productid { get; set; }
        public int count { get; set; }
    
        public virtual product product { get; set; }
        public virtual orders orders { get; set; }
    }
}
